"""Translate the verified 1008:0472 level-rule routine from a Ghidra C export.

Usage: python port-beebop2-rules.py decompiled.c generated/level-transitions.js
Rendering calls are removed; game-state assignments retain their original order.
The generated module contains JavaScript conditions, not a bytecode interpreter.
"""
from pathlib import Path
import re
import sys

source = Path(sys.argv[1]).read_text()
source = source.split('// 1008:0472 FUN_1008_0472', 1)[1].split('// 1008:1135', 1)[0]
source = source[source.index('{') + 1:source.rindex('}')]
source = re.sub(r'  (?:int unaff_BP|undefined2 \*puVar1|bool bVar2);\n', '', source)
source = re.sub(r'FUN_1038_03cb\([^;]+;', '', source)
source = re.sub(r'SETRECT\([^;]+;', '', source)
source = re.sub(r'FUN_1028_7ad9\([^;]+;', '', source)
source = re.sub(r'puVar1 = [^;]+;', '', source)
source = re.sub(r'FUN_1038_0b84\((0x[0-9a-f]+),0x1040,0x19ec,0x1040\);',
                lambda m: f'bVar2 = equalBoard(state, "{m[1][2:]}");', source)
source = source.replace('(FUN_1038_0b84(0x18f4,0x1040,0x19ec,0x1040), bVar2)', 'equalBoard(state, "18f4")')
source = source.replace('FUN_1008_0289()', 'openGate(state)')
source = re.sub(r'DAT_1040_(1a[0-9a-f]{2}|19f[0-9a-f])',
                lambda m: f'state.cells[{int(m[1],16)-0x19ed}]', source)
source = source.replace("'0'", '48')
source = source.replace('DAT_1040_6bcc', 'state.stage')
source = re.sub(r'DAT_1040_([0-9a-f]{4})', lambda m: f'r["{m[1]}"]', source)
source = re.sub(r'\n\s*\n', '\n', source)
assert not re.search(r'FUN_|DAT_|undefined|SETRECT|puVar', source)
header = '''// Generated by web/tooling/port-beebop2-rules.py; BeeBop II 1008:0472.
// Compare each board byte, including undestroyed walls, as Pascal strings do.
function equalBoard(state, key) {
  return state.level.boards[key].length === state.cells.length &&
    state.level.boards[key].every((value, index) => value === state.cells[index]);
}

export function runLevelTransitions(state, openGate) {
  const r = state.rules;
  let bVar2;
'''
Path(sys.argv[2]).parent.mkdir(parents=True, exist_ok=True)
Path(sys.argv[2]).write_text(header + source + '}\n')
